# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import datanode_pb2 as datanode__pb2


class DataNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteChunk = channel.unary_unary(
                '/DataNodeService/WriteChunk',
                request_serializer=datanode__pb2.ChunkWriteRequest.SerializeToString,
                response_deserializer=datanode__pb2.ChunkWriteResponse.FromString,
                )
        self.ReadChunk = channel.unary_unary(
                '/DataNodeService/ReadChunk',
                request_serializer=datanode__pb2.ChunkReadResponse.SerializeToString,
                response_deserializer=datanode__pb2.ChunkReadResponse.FromString,
                )


class DataNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteChunk,
                    request_deserializer=datanode__pb2.ChunkWriteRequest.FromString,
                    response_serializer=datanode__pb2.ChunkWriteResponse.SerializeToString,
            ),
            'ReadChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChunk,
                    request_deserializer=datanode__pb2.ChunkReadResponse.FromString,
                    response_serializer=datanode__pb2.ChunkReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataNodeService/WriteChunk',
            datanode__pb2.ChunkWriteRequest.SerializeToString,
            datanode__pb2.ChunkWriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataNodeService/ReadChunk',
            datanode__pb2.ChunkReadResponse.SerializeToString,
            datanode__pb2.ChunkReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
