# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namenode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enamenode.proto\"\"\n\x06Socket\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"Z\n\rChunkLocation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63hunkId\x18\x02 \x01(\x05\x12\x11\n\treplicaId\x18\x03 \x01(\x05\x12\x17\n\x06socket\x18\x04 \x01(\x0b\x32\x07.Socket\"#\n\x07Sockets\x12\x18\n\x07sockets\x18\x01 \x03(\x0b\x32\x07.Socket\"2\n\x05\x43hunk\x12\x0f\n\x07\x63hunkId\x18\x01 \x01(\x03\x12\x18\n\x07sockets\x18\x02 \x03(\x0b\x32\x07.Socket\"6\n\x0c\x46ileMetadata\x12\x0e\n\x06\x66ileId\x18\x01 \x01(\t\x12\x16\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\x06.Chunk\"(\n\x08Metadata\x12\x1c\n\x05\x66iles\x18\x01 \x03(\x0b\x32\r.FileMetadata\"\r\n\x0bVoidRequest\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t27\n\x0bLocateChunk\x12(\n\x0bLocateChunk\x12\x0e.ChunkLocation\x1a\t.Response2,\n\tHeartBeat\x12\x1f\n\tHeartBeat\x12\x07.Socket\x1a\t.Response2Y\n\x05\x46\x65tch\x12%\n\x0b\x46\x65tchSocket\x12\x0c.VoidRequest\x1a\x08.Sockets\x12)\n\x0e\x46\x65tchLocations\x12\x0c.VoidRequest\x1a\t.Metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'namenode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOCKET']._serialized_start=18
  _globals['_SOCKET']._serialized_end=52
  _globals['_CHUNKLOCATION']._serialized_start=54
  _globals['_CHUNKLOCATION']._serialized_end=144
  _globals['_SOCKETS']._serialized_start=146
  _globals['_SOCKETS']._serialized_end=181
  _globals['_CHUNK']._serialized_start=183
  _globals['_CHUNK']._serialized_end=233
  _globals['_FILEMETADATA']._serialized_start=235
  _globals['_FILEMETADATA']._serialized_end=289
  _globals['_METADATA']._serialized_start=291
  _globals['_METADATA']._serialized_end=331
  _globals['_VOIDREQUEST']._serialized_start=333
  _globals['_VOIDREQUEST']._serialized_end=346
  _globals['_RESPONSE']._serialized_start=348
  _globals['_RESPONSE']._serialized_end=389
  _globals['_LOCATECHUNK']._serialized_start=391
  _globals['_LOCATECHUNK']._serialized_end=446
  _globals['_HEARTBEAT']._serialized_start=448
  _globals['_HEARTBEAT']._serialized_end=492
  _globals['_FETCH']._serialized_start=494
  _globals['_FETCH']._serialized_end=583
# @@protoc_insertion_point(module_scope)
